### ISSUE TITLE
[TAB-439] Provide abstraction of pagination in webserver graphql api

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#1038]
Reference: [https://github.com/dyedgreen/juniper-relay](https://github.com/dyedgreen/juniper-relay) (not directly usable, but can be used as a reference).

Steps:

- [X] \#1107
- [X] Frontend switch to new graphql api, build proper pagination support for users and members in page
- [X] Remove old `users` and `invitations`, and rename `usersNext` / `invitationsNext` 's `Next` suffix.

<sub>From [SyncLinear.com](https://synclinear.com) | [TAB-439](https://linear.app/tabbyml/issue/TAB-439/provide-abstraction-of-pagination-in-webserver-graphql-api)</sub>

**Comment by wsxiaoys** [comment]
bug

```
users(first: 5, after: "4") -> {
  hasPreviousPage: false
}
```

**Comment by wsxiaoys** [comment]
please fill the details of bug (including the graphql query in graphql playground @jueliang)

**Comment by liangfung** [comment]
For example, there are 4 users in my local server
![all users](https://github.com/TabbyML/tabby/assets/17516233/71bb9175-0993-4641-b51d-9f4d713af23d)
When I query the users after cursor '2',  the `hasPreviousPage` field returns `false`. Expecting returns `true` because  there are cursor '1' and cursor '2' as the previous page.
<img width="1553" alt="image" src="https://github.com/TabbyML/tabby/assets/17516233/51a7019d-b7d0-42b9-83f5-bd9b59872f9c">
