### ISSUE TITLE
how to set authentication token?

### ISSUE THREAD

**Issue by tristanyin** [TabbyML/tabby#1159]
**Describe the bug**
Can't use the VS code due to authentication token issue

**Information about your version**
tabby 0.2.1

**Information about your GPU**
it is on my Mac M1 Chip

**Additional context**
installed tabby on my mac using "brew". I can start the tabby server. However, when I try to use tabby VS extension, I saw this pop-up.

<img width="643" alt="Screenshot 2024-01-03 at 20 54 07" src="https://github.com/TabbyML/tabby/assets/108164399/72204ead-27be-4d3b-af75-288b3eed1592">

My config is here:

\## You can set the server endpoint here and an optional authentication token if required.
\# [server]
endpoint = "http://localhost:8080" # http or https URL
\# token = "your token" # if token is set, request header Authorization = "Bearer $token" will be added automatically

I haven't set the token field here. Does this mean that the authentication is not enabled?

Tried to look thru the manual for the answers, but it seems the part about authentication token is not clear. 

This may not be a bug, but I am stuck here. Your help will be appreciated.

**Comment by icycodes** [comment]
Hi, @tristanyin!

I noticed that you have enabled the `--webserver` feature for your Tabby server. With this feature enabled, you'll need a token to access the API. You can find the token by accessing `http://localhost:8080` in your browser.

Please note that `~/.tabby-client/agent/config.toml` is a client-side configuration file. Both the token set in VSCode and in `~/.tabby-client/agent/config.toml` should work, with the settings in VSCode having higher priority.

Since this configuration file uses TOML syntax, you also need to uncomment the line `[server]` in the file. Here's an example of how it should look:
```
## You can set the server endpoint here and an optional authentication token if required.
[server]
endpoint = "http://localhost:8080/"
token = "your token"
```

**Comment by tristanyin** [comment]
@icycodes thanks for the reply.  Is there any alternative that you recommend?  will the version of Tabby in brew be updated? Or is there a way I can downgrade the client version?

**Comment by icycodes** [comment]
The latest version of the Tabby server is 0.7.0, available on Homebrew. It is recommended to check and upgrade to this version.

Alternatively, you can downgrade the VSCode extension to version 1.0.0 by using 'Install another version...'
![Screenshot 2024-01-04 093724](https://github.com/TabbyML/tabby/assets/13573879/e44bca85-7193-471a-8572-976a4a56b964)

**Comment by tristanyin** [comment]
it worked. Many thanks!
