### ISSUE TITLE
[TAB-447] Ability to configure nodeBinary (for Intellij users) via client config.toml

### ISSUE THREAD

**Issue by sundaraa-deshaw** [TabbyML/tabby#1232]
**Please describe the feature you want**
As of today, client agent config allows to configure, endpoint, token, headers, timeout, usage tracking. It will be good to configure nodeBinary via this config, so that users do not have to remember to punch this in the IJ settings panel

**Additional context**

---
Please reply with a 👍 if you want this feature.

<sub>[TAB-447](https://linear.app/tabbyml/issue/TAB-447/ability-to-configure-nodebinary-for-intellij-users-via-client)</sub>

**Comment by icycodes** [comment]
Hi, @sundaraa-deshaw,

I understand that you would like to have all these configurations summarized in one place. However, it is not recommended to add the nodeBinary configuration to the `.tabby-client/agent/config.toml` file.

The reason is that the config.toml file is only read in the agent, which is dependent on the running nodeBinary. Therefore, if I want to add the nodeBinary in config.toml, it will require reading the config.toml file in the IntelliJ plugin (or vim) and would increase complexity and dependencies.

However, the IntelliJ plugin already provides a clear and convenient way to set the nodeBinary in the IDE settings page. (the vim plugin uses global variables.)

Considering these factors, I don't think it is a good choice to add this feature at the moment.
