### ISSUE TITLE
mac install faild, arm64 arch

### ISSUE THREAD

**Issue by yuyang0914** [TabbyML/tabby#1542]
command is
➜ ~ brew install tabbyml/tabby/tabby
tabby: The arm architecture is required for this software.
Error: tabby: An unsatisfied requirement failed this build.

➜  ~ arch
arm64

I don’t know why it prompts like this when brew install

**Comment by wsxiaoys** [comment]
Likely your homebrew installation is problematic, thus caused the detection failed.

Might consider search issues in https://github.com/Homebrew/brew

**Comment by alekseiapa** [comment]
Probably your homebrew configuration indicates that you're running the x86_64 version of Homebrew under Rosetta 2 instead of the native ARM (arm64) version required for M1 Macs.

Run the following command to install the ARM version of Homebrew in /opt/homebrew:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Update Your Shell to Use the ARM Version

```
nano ~/.zshrc
```

Add the following line at the top of the file:

```
export PATH="/opt/homebrew/bin:$PATH"
```


Save and exit (Ctrl+O, Enter, Ctrl+X), then reload the configuration:
```
source ~/.zshrc
```


Verify the Correct Architecture Confirm that the arch command points to the ARM-based Homebrew:

```
arch -arm64 brew config
```


Reinstall tabby:
```
brew install tabbyml/tabby/tabby
```
