### ISSUE TITLE
[error] [TabbyAgent] Fetch server config error

### ISSUE THREAD

**Issue by zoky28** [TabbyML/tabby#1602]
i got [error] [TabbyAgent] Fetch server config error

**Comment by icycodes** [comment]
Hi, @zoky28 
This error can be safely ignored. 
This feature was added in the recent version of the Tabby IDE extension to support the server-provided config since Tabby server v0.9. It should have no effect when connecting to a Tabby server < 0.9. 

I will adjust the log level to avoid any misunderstandings.
