### ISSUE TITLE
Agent: Add an Interface to Sync Configuration

### ISSUE THREAD

**Issue by icycodes** [TabbyML/tabby#162]
Now we only have an interface `setServerUrl` in agent. 
We should use a better interface to sync configuration between editor and agent.

* [ ] Track Usage Analytics in agent, add an config to disable usage tracking.

**Comment by wsxiaoys** [comment]
Would it be easier if:
1. Keep the configuration always persistent in `~/.tabby/agent.toml`.
2. When the agent starts and there's no `~/.tabby/agent.toml` file, the agent will automatically create a default version.
3. Instead of having settings in each IDE extension, we can expect users to directly modify `~/.tabby/agent.toml`. This means we no longer need the "Set Server URL" option in VSCode, but we can have a "Tabby: Settings" option that opens `~/.tabby/agent.toml` for editing.

**Comment by icycodes** [comment]
Using a config file in user configuration folder could help share tabby config across IDEs, but may have disadvantages:

1. Only agent options can be shared. Many configuration such as `toggle enable / disable` or other UI settings, are not interesting to agent, so they will not be send to agent. We will always have to save them in IDE extension. Use `VSCode User/Workspace Config File` or `setting global variables in vimrc` is a common way to store these configs. And I think it is not good to separate configs and save agent part in Tabby config file but save others in IDE config file.
2. If I want to use different agent configuration for each IDE, I also have to specify config file for each.

And keeping configuration in VSCode will also be helpful to sync configuration across different devices, if you login and enable sync in VSCode.

**Comment by icycodes** [comment]
Completed in #209
