### ISSUE TITLE
Enable adapters for OpenAI Models

### ISSUE THREAD

**Issue by Nitschi** [TabbyML/tabby#1664]
It's great to be able to use these Open-Source Models in such an easy way. In some complex pieces of Software the current models may not always create helpful completions.
Is there a way to integrate the OpenAI Service with tabby, so we can use pay-per-use Code completion powered by both GPT-4-turbo and the tabby engine that collects the necessary context in the IDE?
When new Open-Source Models become available the switch would be extremely easy as well.
That would be amazing!

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
It's actually doable due to an internal experimental flag. However, it's probably not very useful for code completion scenarios due to latency. It might be helpful for chat playground use cases, especially once we integrate it with the code browser.

Marked as a documentation improvement to be determined.

**Comment by Wolfsauge** [comment]
I'm somewhat confused.. on the one hand latency is an issue? And then https://github.com/TabbyML/tabby/issues/2176#issue-2303739301 shall bring in ollama support?

Sorry, but I don't understand what's the difference between running a model in Huggingface TGI or vLLM (or ...) using the OpenAI-compatible locally in some podman container, and how that is providing for a worse latency, that doesn't justify implementing it, but ollama support should go in?

There are a number of other pieces of software which I am using everyday, that provide an OpenAI-compatible API.

And I'm somewhat unhappy about tabbyml being limited to GGUFs. I was told this limitation was due to specific constraints regarding the auto-complete.

Okay, I have to say the tabbyml autocomplete is working fine. But I'd really welcome to focus on more general features, like a general OpenAI-compatible HTTP back end being possible to use within tabbyml, instead of limiting it to ollama, which is kind of a proprietary back end.

Everytime I want to use my Meta Llama 3 8B Instruct model, which is running locally in 1x 3090 at bfloat16 size, I have to stop tabbyml, and use something like Continue instead, in order to be able to do that. Why does tabbyml not allow me to talk to arbitrary OpenAI-compatible APIs?

And how has implementing ollama now got a higher priority than a more general OpenAI-compatible API approach everyone could benefit from? @wsxiaoys

**Comment by wsxiaoys** [comment]
Documented at https://tabby.tabbyml.com/docs/administration/model/
