### ISSUE TITLE
Tabby does not use models cache

### ISSUE THREAD

**Issue by flavienbwk** [TabbyML/tabby#330]
**Describe the bug**

Tabby re-downloads the models even when locally downloaded.

Docker-compose configuration : 

```yaml
version: '3.5'
services:
  tabby:
    restart: always
    build: .
    command: serve --model TabbyML/SantaCoder-1B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
```

Output with an empty `~/.tabby/models/TabbyML` folder :

```bash
root@mycomputer:~/tabby# docker-compose logs -f
tabby-tabby-1  | 2023-08-03T11:30:48.328833Z  INFO tabby_download: crates/tabby-download/src/lib.rs:66: Start downloading model `TabbyML/SantaCoder-1B`
```

The model is downloaded in my local directory :

```bash
root@mycomputer:~/tabby#  ls ~/.tabby/models/TabbyML
SantaCoder-1B
```

Output with the previous `~/.tabby/models/TabbyML` folder :

```bash
root@mycomputer:~/tabby# docker-compose logs -f
tabby-tabby-1  | 2023-08-03T11:34:36.160658Z  INFO tabby_download: crates/tabby-download/src/lib.rs:66: Start downloading model `TabbyML/SantaCoder-1B`
```

**Information about your GPU**

```txt
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:01:00.0 Off |                    0 |
| N/A   34C    P0    25W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Additional context**

Worked on a computer without internet connection before last update (last Docker image before update).

**Comment by wsxiaoys** [comment]
Hi @flavienbwk 

Thank you for the feedback. Just to confirm, are there any logs showing that tabby has started and is listening at :8080? If not, it could mean that the model hasn't finished downloading, resulting in invalid cache.

**Comment by flavienbwk** [comment]
Hi @wsxiaoys. On my computer disconnected from internet, I get a "failed to fetch" error. On my online computer, it starts after the logs show.

**Comment by wsxiaoys** [comment]
Ah, I apologize for just noticing this additional information:

> Worked on a computer without internet connection before last update (last Docker image before update).

This commit (https://github.com/TabbyML/tabby/commit/6a50902ca733c96cc2a3a4be492b209c7105a655) invalidates the local cache since additional optional files are required to check against the server side. So, when the latest Docker image checks if the local cache has validated vocabulary.json (which is missing from the local cache metadata), it tries to access the internet and retrieve its verified version.

This issue should be handled more carefully in order to avoid breaking the cache for revision 6, or it should be resolved through a major version bump in a semantic version setup. This way, users can decide whether to opt-in for the new version. Unfortunately, since we are still in the alpha phase, such a process has not been set up yet.

You should be able to work around this issue by:
1. Using an older image.
2. Updating the cache with the new image.
Sorry for any inconvenience caused.

**Comment by flavienbwk** [comment]
Thank you for your quick reply. Downloading the models all over again seem to work! Thanks.
