### ISSUE TITLE
Locally building on a M1

### ISSUE THREAD

**Issue by V0lkanTas** [TabbyML/tabby#332]
**Describe the bug**
I came across a build issue with regards to ctranslate2:
```
CMake Error at CMakeLists.txt:5 (add_subdirectory):
    The source directory

      /Users/xxx.yyy/code/tabby/crates/ctranslate2-bindings/CTranslate2

    does not contain a CMakeLists.txt file.
```

I was able to solve this by running: 
``` 
git submodule update --init --recursive
```

I guess the submodule are either not initialized properly or require an update? 
Would it be ok to update the submodules and push changes up?

Kind Regards,

**Comment by wsxiaoys** [comment]
Hi,

To clone a repository with a submodule, you have two options. You could either use the command `git clone --recursive`, or you can perform a `git clone` first and then execute `git submodule update --init --recursive`.

So, what you're currently doing aligns with the expected behavior of git submodules.

**Comment by V0lkanTas** [comment]
Gotcha, thank you for the knowledge transfer. I will close this issue.
