### ISSUE TITLE
Comply XDG in suggested setup

### ISSUE THREAD

**Issue by xeruf** [TabbyML/tabby#441]
**Please describe the feature you want**

The default volume mount should not be in HOME, i.e. replace `$HOME/.tabby:/data` with `${XDG_DATA_HOME:-$HOME/.config}/tabby:/data`.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics

---
Please react with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
The suggestion seems to be the correct way to use the data directory. However, I prefer not to change it for the following reasons:

1. We would likely keep `TABBY_ROOT = ~/.tabby` in the Rust binary as we want to maintain backward compatibility.
2. Because of the first point, we would like to keep the default Docker command unchanged.

Considering that there is a workaround available (`export TABBY_ROOT=$XDG_DATA_HOME/tabby`), it might be best to leave this as it is.

**Comment by xeruf** [comment]
> We would likely keep TABBY_ROOT = ~/.tabby in the Rust binary as we want to maintain backward compatibility.

Well in the code you could check whether XDG_DATA_HOME is set (which means the user explicitly endorses XDG), and if not fall back to the old dot directory.

**Comment by wsxiaoys** [comment]
> > We would likely keep TABBY_ROOT = ~/.tabby in the Rust binary as we want to maintain backward compatibility.
> 
> Well in the code you could check whether XDG_DATA_HOME is set (which means the user explicitly endorses XDG), and if not fall back to the old dot directory.

What if XDG_DATA_HOME is already being set on certain platforms we've previously ignored? 🤔
