### ISSUE TITLE
Can tabby-agent support service-based deployment, so that the node environment does not need to be installed in idea and vim?

### ISSUE THREAD

**Issue by hufeng** [TabbyML/tabby#480]
![image](https://github.com/TabbyML/tabby/assets/533008/4ee677bc-0622-44ad-9118-1f08095d9a1f)

**Comment by wsxiaoys** [comment]
The `tabby-agent` is not designed to support service-based deployment, as its primary function is at the user session level.

Implementing optimizations such as keystroke level caching, cancellation, and debouncing requires a user session level interface. While the logic for these optimizations can be implemented in each individual IDE, doing so would make the code difficult to maintain. Therefore, we've extracted `tabby-agent` to share common logic at the user session level, facilitating consistent and maintainable optimization implementations across various IDEs.

There is a similar and popular concept known as the Language Server Protocol (LSP) that defines a standard protocol for user session level interactions. However, `tabby-agent` currently does not expose an LSP interface due to certain trade-offs, but that's another story.

**Comment by hufeng** [comment]
Yes, LSP is a good design.

In the future, can we consider building tabby-agent using rust, so that we can generate wasm or local executable files that do not rely on external runtime (like node).

**Comment by wsxiaoys** [comment]
While, but doesn't WebAssembly itself require a Node runtime? For now, I think we're good sticking with a JavaScript-based implementation for the agent.
