### ISSUE TITLE
CTranslate2 on Mac?

### ISSUE THREAD

**Issue by Janaka-Steph** [TabbyML/tabby#503]
Is there a typo here https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md?plain=1#L48 ? 
I suppose you meant `Tabby utilizes GGML for inference on the metal device`.

Also on mac M1, the download command will pull both GGML and CTranslate2 files. Why is that? I suppose CTranslate2 files are not necessery on M1?

**Comment by wsxiaoys** [comment]
Thanks for the information, fixing the issue in #504

> Also on mac M1, the download command will pull both GGML and CTranslate2 files. Why is that? I suppose CTranslate2 files are not necessery on M1?

Currently, the default behavior of the download command is to download both CTranslate2 and GGML files. This is because you might still use the CPU backend, powered by CTranslate2, on Mac. However, please note that this behavior might change in the future.

**Comment by Janaka-Steph** [comment]
Awesome, thank you :)
