### ISSUE TITLE
can support CodeLlama-34b？

### ISSUE THREAD

**Issue by hellobiek** [TabbyML/tabby#540]
**Please describe the feature you want**
can support codellama-34b?

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by hellobiek** [comment]
that means how to transfor other model to tabby format?

**Comment by wsxiaoys** [comment]
The document at https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md provides instructions on creating a Tabby-compatible model repository. You may also use https://huggingface.co/TabbyML/CodeLlama-7B/blob/main/tabby.json as a reference.

However, converting CodeLlama-34B may not be very practical for Tabby due to the following reasons:

ctranslate2 doesn't support tensor parallelism, meaning you would need hardware like an A100-80G to load a 34B model (or A100-40G for int8 computation mode).
For ggml-backed metal inference, it would require approximately 34GB of RAM.
Considering the high barriers outlined in points 1 and 2, we currently do not maintain a repository for the 34B model.

**Comment by dbalabka** [comment]
@wsxiaoys , thanks for the update about the 34B models. I have a related question. Does Tabby support CTranslate int8 inference? If so, how to enable it? 

Also, it would be great if you could provide a step-by-step guide on how to deploy the 34B model. Thanks in advance!

**Comment by IncubatorShokuhou** [comment]
@wsxiaoys , it would be immensely helpful if more detailed instructions on creating a Tabby-compatible model repository could be provided!

**Comment by hellobiek** [comment]
> The document at https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md provides instructions on creating a Tabby-compatible model repository. You may also use https://huggingface.co/TabbyML/CodeLlama-7B/blob/main/tabby.json as a reference.
> 
> However, converting CodeLlama-34B may not be very practical for Tabby due to the following reasons:
> 
> 1. ctranslate2 doesn't support tensor parallelism, meaning you would need hardware like an A100-80G to load a 34B model (or A100-40G for int8 computation mode).
> 2. For ggml-backed metal inference, it would require approximately 34GB of RAM.
> 
> Considering the high barriers outlined in points 1 and 2, we currently do not maintain a repository for the 34B model.
