### ISSUE TITLE
Garbled characters when using Chinese characters

### ISSUE THREAD

**Issue by IncubatorShokuhou** [TabbyML/tabby#600]
**Describe the bug**
When I use tabby (starcoder-3b) and use Chinese for code comments, garbled characters appear; as shown below:

```
    Args:
        df_dict (pd.DataFrame): 包含站点5分钟最大风速数据的DataFrame
        var (str): 风速变量名称
        time_of_data (datetime): 数据时间
        lon_start (float): 经度范围起始值
        lon_end (float): 经度范围结束值
        lat_start (float): 纬度范围起始值
        lat_end (float): 纬度范围结束值
        interval (float): 网格间隔
        use_fg (bool, optional): 是否使用第一猜测场.
        gfs_host (str, optional): **缃戞牸鍖栨彃鍊兼湇鍔″櫒鍦板潃.**
```
I'm using pycharm and don't have any other code completion plugins turned on
**Information about your GPU**
```
Fri Oct 20 13:57:18 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.103                Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        On  | 00000000:01:00.0  On |                  N/A |
|  0%   47C    P8               8W / 170W |   5365MiB / 12288MiB |      7%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
**Additional context**

**Comment by IncubatorShokuhou** [comment]
> Unfortunately, none of the base models listed in the Model Directory are training their tokenizer for Chinese. e.g StarCoder-3B: https://huggingface.co/TabbyML/StarCoder-3B/raw/main/tokenizer.json

Thank you

**Comment by sctop** [comment]
Though this issue is closed, I would say it's no surprise that TabbyML (specifically, `starcoder-1b`) doesn't train for Chinese.

But I'd like to point out that the model seemed to be up for something when I was writing a description for a page... if it ever outputs something correctly.

![image](https://github.com/TabbyML/tabby/assets/26916108/6adc5c73-1ae6-42cd-9957-85241a628573)

translation: This page lists the changelogs for the repo {{ changelog.repo_info.repo_name }}. This changelog is maintained manually and therefore, there could be some delays in updating the logs; for more details, please [refer to the link shown above.]

Despite the fact that the model still got my intent wrong, it actually makes sense to refer to a release page later in the page. This phenomenon can be easily reproduced in text completion (rather than code completion).

**Comment by wsxiaoys** [comment]
Agree, it's a pity to observe case like this.

Filing issue https://github.com/TabbyML/tabby/issues/603, please 👍 if you wanna this feature being prioritized.

**Comment by ClarkWain** [comment]
I run CodeLlama7B model on Tabby，I found that when it auto-completes Chinese comments, there is gibberish appearing. However, when I tried CodeLlama7B on HuggingFace, it seems to support Chinese.

What could be the reason for this discrepancy?

![chinese](https://github.com/TabbyML/tabby/assets/2370865/283ac56a-e4bf-4c10-8560-9e6ac9d03bfc)
![chinese2](https://github.com/TabbyML/tabby/assets/2370865/9ab834a4-fcd3-4e78-98fa-2cf33a2501c4)
