### ISSUE TITLE
using cpu mode

### ISSUE THREAD

**Issue by paneda1998** [TabbyML/tabby#69]
Hey guys,

Is there a specific reason why you removed the CPU mode from the project readme's description? If access to GPU is not available, is there an alternative way to run the project?

**Comment by paneda1998** [comment]
and can you please tell what is the minimum required gpu system that we need for running this project properly?

**Comment by wsxiaoys** [comment]
The CPU mode was added for development/CI purposes but lacks some important features like stop words. Additionally, the user experience would be extremely poor since users would have to hold their keystrokes for 10 seconds or more for simple completion.

We will reexamine CPU support once https://github.com/ggerganov/ggml becomes more stable.

> and can you please tell what is the minimum required gpu system that we need for running this project properly?

For the demo model (TabbyML/J-350M), it is recommended to run it with a GPU card that has more than 8GB RAM to have a decent experience.

**Comment by wsxiaoys** [comment]
Related #66

**Comment by paneda1998** [comment]
thanks for your answer!
