### ISSUE TITLE
Improve command line error handling in tabby's CLI interface

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#846]
For now we have `unwrap` / `expect` here and there, they caused panic and generates unfriendly error message to users.

We should review them in package scenario and generate proper terminal error message instead

- [ ] [tabby-common](https://github.com/search?q=repo%3ATabbyML%2Ftabby+path%3A%2F%5Ecrates%5C%2Ftabby-common%5C%2F%2F+unwrap&type=code)
- [ ] [tabby-download](https://github.com/search?q=repo%3ATabbyML%2Ftabby+path%3A%2F%5Ecrates%5C%2Ftabby-download%5C%2F%2F+unwrap&type=code)
- [ ] [tabby-scheduler](https://github.com/search?q=repo%3ATabbyML%2Ftabby+path%3A%2F%5Ecrates%5C%2Ftabby-scheduler%5C%2F%2F+unwrap&type=code)
- [ ] [tabby-webserver](https://github.com/search?q=repo%3ATabbyML%2Ftabby+path%3A%2F%5Eee%5C%2Ftabby-webserver%5C%2F%2F+unwrap&type=code)

**Comment by DionysusG** [comment]
Hey, there. I've skimmed the code snips that involve  `unwrap / expect` and there are mostly two scenario:
1. straightforward problems, illegal format, no file name, etc. We should just call out the problem instead of `unwrap` them.
2. problems that require closer examinations, like `unwrap` of requested webpages. I need more context to determin how to deal with them, panic, retry, or others.

I will fix problems of `senario 1` with a commit, and that of `senario 2` with another. We should discuss problems of `senario 2` in PR code review. Does it sound like a plan?

**Comment by wsxiaoys** [comment]
@DionysusG sorry I missed your response, that sounds good to me! Look forward to it!
